# Generated by Django 6.0.8 on 2026-08-06 05:04

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_soal', models.CharField(max_length=200)),
                ('mapel', models.CharField(max_length=100)),
                ('file_zip', models.FileField(upload_to=portal.models.path_soal_zip)),
                ('folder_ekstrak', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
