# Generated by Django 6.0.8 on 2026-08-12 03:41

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_banksoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banksoal',
            name='file_zip',
            field=models.FileField(blank=True, null=True, upload_to=portal.models.path_soal_zip),
        ),
        migrations.AlterField(
            model_name='slidebanner',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='slidebanner',
            name='judul',
            field=models.CharField(max_length=200),
        ),
    ]
