# Generated by Django 6.0.8 on 2026-08-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_banksoal_file_zip_alter_slidebanner_gambar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriPembelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('kelas', models.CharField(choices=[('X', 'Kelas X'), ('XI', 'Kelas XI'), ('XII', 'Kelas XII')], default='X', max_length=5)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(max_length=500)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='modul_pdf/')),
                ('kkm', models.IntegerField(default=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
