# Generated by Django 6.0.8 on 2026-08-15 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_materipembelajaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='materipembelajaran',
            name='has_post_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='materipembelajaran',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='SoalPostTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('opsi_a', models.CharField(max_length=255)),
                ('opsi_b', models.CharField(max_length=255)),
                ('opsi_c', models.CharField(max_length=255)),
                ('opsi_d', models.CharField(max_length=255)),
                ('opsi_e', models.CharField(max_length=255)),
                ('kunci_jawaban', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_post_test', to='portal.materipembelajaran')),
            ],
        ),
    ]
