# Generated by Django 6.0.8 on 2026-08-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_materipembelajaran_has_post_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materipembelajaran',
            name='file_zip',
            field=models.FileField(blank=True, null=True, upload_to='materi_zip/'),
        ),
        migrations.AddField(
            model_name='materipembelajaran',
            name='folder_ekstrak',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
