# Generated by Django 6.0.8 on 2026-08-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_materipembelajaran_file_zip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materipembelajaran',
            name='mapel',
            field=models.CharField(choices=[('Informatika', 'Informatika'), ('Matematika', 'Matematika'), ('Fisika', 'Fisika'), ('Kimia', 'Kimia'), ('Biologi', 'Biologi'), ('Bahasa Indonesia', 'Bahasa Indonesia'), ('Bahasa Inggris', 'Bahasa Inggris'), ('Sejarah', 'Sejarah'), ('Sosiologi', 'Sosiologi'), ('Ekonomi', 'Ekonomi'), ('Geografi', 'Geografi'), ('PJOK', 'PJOK'), ('Seni Budaya', 'Seni Budaya'), ('PPKn', 'PPKn'), ('PAI', 'Pendidikan Agama Islam')], default='Informatika', max_length=100, verbose_name='Mata Pelajaran'),
        ),
    ]
