# Generated by Django 6.0.8 on 2026-08-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_materipembelajaran_mapel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Game')),
                ('category', models.CharField(default='Edukasi', max_length=100, verbose_name='Kategori Game')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi Game')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='game_covers/', verbose_name='Gambar Sampul')),
                ('file_zip', models.FileField(blank=True, null=True, upload_to='game_zips/', verbose_name='File ZIP HTML5 Game')),
                ('game_url', models.URLField(blank=True, null=True, verbose_name='URL Game Eksternal (Optional)')),
                ('folder_ekstrak', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
