# Generated by Django 6.0.8 on 2026-08-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
