# Generated by Django 6.0.8 on 2026-08-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrosswordGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Teka-Teki Silang')),
                ('kategori', models.CharField(default='Informatika', max_length=100, verbose_name='Kategori/Mata Pelajaran')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi/Petunjuk Umum')),
                ('pin', models.CharField(max_length=6, unique=True, verbose_name='PIN Game (6 Angka/Huruf)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
